config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses , only: [:new, :create]
  end
  resources :doses, only: [:destroy]

# we want to not destory the cocktail id so delete for dose is separate

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many  :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true

  # JOIN ingredients ON dose.ingredient_id = dose.id
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktails
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end

  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

private
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end



end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]


  def new
    @ingredients = Ingredient.all - @cocktail.ingredients
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
     if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        @ingredients = Ingredient.all - @cocktail.ingredients
        #you need to reload the ingredients
        render :new
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    # look at routes for url pattern
    cocktail = dose.cocktail
    dose.destroy
    # it'll return the cocktail
    redirect_to cocktail_path(cocktail)
  end

 private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end


# params from form, cocktail from url

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
<%= f.input :name %>
<%= f.submit "Confirm Edit", class: "btn btn-danger" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url(<%=image_path "CT.png"%>);">
  <div class="banner-content">
    <h1>Sizzzurp</h1>
    <p>Create your own cocktail</p>
    <div class="btn">
      <%= link_to 'Mix One', new_cocktail_path, :class => "btn-lg btn-danger" %>
    </div>
  </div>
</div>

<!-- <div class="wrapper"> -->
  <div class="container">
    <h2 class="text-center">Cocktails</h2>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="cards">
          <div class="card">
            <%= link_to image_tag("drink_pink_bg_lighter.png", class: "card-body"), cocktail_path(cocktail)%>
            <div class="card-category">
              <h3>
                <%= cocktail.name %>
              </h3>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>
<!-- </div> -->

app/views/cocktails/new.html.erb
<div class="text-center">
  <h1>Add a cocktail!</h1>
</div>

<div class="text-center">
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <p>
    <%= f.submit class: "btn btn-danger" %>
  </p>
</div>
<% end %>


<p class="text-center">
  <%= link_to 'Back', cocktails_path, class: "btn btn-danger" %>
</p>




<!-- simple_for_for
1.generates path based on objects
2.check the method based on object if the obj is saved method = patch/ else method="post"
3.f.input will know what kind to generate -->


<!-- <form action="/cocktails/<%= @cocktail.id %>/doses" method="post">
</form>

get info from user
send it thorugh the params to a route/controller action
-->

app/views/cocktails/show.html.erb
<h1 class="text-center"><%= @cocktail.name %> </h1>

<div class="text-center">
  <h3><strong>Doses</strong></h3>
</div>

<div class="text-center">
  <ul>
    <% @cocktail.doses.each do |dose| %>
    <li>
      <p><%= dose.description %></p>
      <p><%= dose.ingredient.name %></p>
    </li>
    <%= link_to 'Delete dose', dose_path(dose), method: :delete %>
    <% end %>
  </ul>
</div>

<div class="text-center">
<p>
  <%= link_to 'Add dose', new_cocktail_dose_path(@cocktail), class: 'btn btn-danger' %>
</p>
<p>
  <%= link_to "Edit Cocktail", edit_cocktail_path(@cocktail), class: 'btn btn-danger' %>
</p>
<p>
  <%= link_to 'Back', cocktails_path, class: 'btn btn-danger' %>
</p>
</div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class="text-center">
<h2>Add a dose!</h2>
</div>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
<div class="text-center">
<%= f.input :description,:input_html => {:maxlength => 15, :size => 15}%>
<%= f.input :ingredient_id, collection: @ingredients %>
<%= f.submit class: "btn btn-danger"%>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render partial: "shared/navbar" %>
  <%= yield %>
  <%= render partial: "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Drink with <i class="fa fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="<%=image_path "logo.png"%>" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Cocktails</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">About Us</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>